[package]
name = "rustcolony"
version = "0.1.0"
edition = "2021"
authors = ["Fish"]
description = "A real-time colony simulation with autonomous entities and ecosystem dynamics"
license = "MIT"

[dependencies]
minifb = "0.25"
rand = "0.8"

[[bin]]
name = "rustcolony"
path = "src/main.rs" 